# Specify substitutions to allow easy name re-use
substitutions:
  device_name: esp32cam01
  friendly_name: ESP32CAM01

# Main config begins
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} Fallback Hotspot
    password: !secret ap_password

captive_portal:

# Camera web server
web_server:
  port: 80

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

# Camera configuration
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 5 fps
  idle_framerate: 0.05 fps
  jpeg_quality: 10
  resolution: 800x600
  vertical_flip: False
  horizontal_mirror: False
  contrast: 0
  brightness: 0
  saturation: 0
  special_effect: none

  # Image settings
  name: ${friendly_name}

# LED (Flashlight)
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

# GPIO_4 is the LED pin
light:
  - platform: binary
    output: gpio_4
    name: flashlight
